### ISSUE TITLE
error in main.py

### ISSUE THREAD

**Issue by preksha12** [wadhwasahil/Video-Classification-2-Stream-CNN#2]
When I am running main.py below error is coming
preksha@preksha:~/videoclasCNN/spatial$ python main.py
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    model1 = VGG_16('vgg16_weights.h5')
  File "main.py", line 57, in VGG_16
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 849, in load_weights
    for k in range(f.attrs['nb_layers']):
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/attrs.py", line 48, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5a.pyx", line 74, in h5py.h5a.open (h5py/h5a.c:2107)
KeyError: "can't open attribute (Attribute: Can't open object)"

**Comment by wadhwasahil** [comment]
Hi. @preksha12.The weights `model1 = VGG_16('vgg16_weights.h5')` contains incorrect vgg16_weights. So, that's why this error. Download the weights  from [here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3) and run the script again.

**Comment by preksha12** [comment]
Thank you .
No this error is resolved but now this error is coming.
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    model1.compile(optimizer=sgd, loss={"out" : 'categorical_crossentropy'})
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 1113, in compile
    y_train = output.get_output(True)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 970, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 645, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 970, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 645, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 970, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 842, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 496, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 496, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 496, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 496, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 496, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 763, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 324, in get_output
    output = self.activation(output)
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 27, in relu
    return K.relu(x, alpha=alpha, max_value=max_value)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 501, in relu
    assert hasattr(T.nnet, 'relu'), ('It looks like like your version of '
AssertionError: It looks like like your version of Theano is out of date. Install the latest version with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

**Comment by wadhwasahil** [comment]
Did you install bleeding edge Theano?
If not, please install it.
If yes, then update your theano.

**Comment by preksha12** [comment]
when I ran main.py it gave output as 207,what does this mean and  after that 

when i tried to run temporal_vid2img.py then it gave following error
Time taken for 0testing videos: 0:00:00.000160

Traceback (most recent call last):
  File "temporal_vid2img.py", line 62, in <module>
    data_prep()
  File "temporal_vid2img.py", line 48, in data_prep
    fc=frame_count[filename.split('_')[1].split('.')[0]]
KeyError: '7NL-7RLMRDk'

**Comment by stillbreeze** [comment]
207 is the class number for the input image you tested the network on. 
As for the temporal stream, this isn't the updated code. Will soon push it.

**Comment by preksha12** [comment]
Thanks for reply and  how can I get class number for an image as in  the
spatial folder only 2 images are there and dog and cat and I have referred
paper in github link of your's that in case of spatial only task will be
performed on single frame so are these images fetched from some database of
video and is that saved on frame by frame basis and if yes, where it is
getting saved in folder?



On Thu, May 5, 2016 at 3:43 PM, Ashar Javed <notifications@github.com>
wrote:

> 207 is the class number for the input image you tested the network on.
> As for the temporal stream, this isn't the updated code. Will soon push it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wadhwasahil/Video-Classification-2-Stream-CNN/issues/2#issuecomment-217118196>
>



-- 
Regards:-
Preksha Pareek
Asst. Prof.
CSE(CE-Dept)

**Comment by preksha12** [comment]
Is it using CCV dataset and from that dataset any random frames (eg. cat,dog) are extracted ?
If is it so then can you please tell me which file is extracting random frames from any class and can we make it complete dynamic where at run time user will put the video and from that it will compute further

**Comment by stillbreeze** [comment]
The class you are referring to belongs to ImageNet. We pre-train the network on it and fine tune it on the CCV dataset. So, if you're dealing with videos, you don't need to worry about the object-class number mapping for ImageNet. Just load the weights (vgg16_weights.h5) and fine tune it on your own dataset.

As for the CCV dataset, you need to use the scripts in the utility_scripts folder to download it from YouTube and also run the various data cleaning and dictionary creating scripts before you can start with the spatial and temporal model. If you wish to use the whole code as it is, you also need to write the static frames (for spatial) and optical flow frames (for temporal) to some directory instead of obtaining both of these things at training time.
And the model just predicts the per-frame softmax output. You need to convert them to per-video output (maybe use a voting strategy).

**Comment by preksha12** [comment]
After reading your last post I got confused as to what this code is doing and say  I want to use this code as it is so what would be the desired output using** spatial** implementation and what does VGG_16 function is doing?

What I understood from this code is that it will take the pretrained model in terms of weights(vgg16_weights.h5) and then it is testing it on any random image.

**Comment by stillbreeze** [comment]
Sorry, for not clarifying which portions are not updated. Only the temporal section and the utility scripts are partially updated. Spatial stream isn't.
Will probably update it by the end of this month with a complete working project.

**Comment by preksha12** [comment]
In spatial stream also I have confusion that what exactly spatial part is doing please elaborate.

**Comment by preksha12** [comment]
I currently executed only main.py and I got class number for dog {That class number is according to imagenet} but should I only run main.py in order to perform classififcation.

**Comment by wadhwasahil** [comment]
hey @preksha12. I will update the code and and so you can train your network on the data-set you like.
Right now, main.py will only give you the class of the object according to the imagenet dataset. 
PS: - You can make frames for each video and train those frames in batches.
Hope I made myself clear.
If you have some more doubt, feel free to mail me at `sahil24wadhwa@gmail.com`
